//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonsterDBEntities : DbContext
    {
        public MonsterDBEntities()
            : base("name=MonsterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Abilities { get; set; }
        public virtual DbSet<Damage_Type> Damage_Type { get; set; }
        public virtual DbSet<Habitat> Habitats { get; set; }
        public virtual DbSet<Loot> Loots { get; set; }
        public virtual DbSet<Monster> Monsters { get; set; }
        public virtual DbSet<Monster_Abilities> Monster_Abilities { get; set; }
        public virtual DbSet<Monster_Habitat_Loot> Monster_Habitat_Loot { get; set; }
        public virtual DbSet<Monster_Resistances> Monster_Resistances { get; set; }
        public virtual DbSet<Monster_Traits> Monster_Traits { get; set; }
        public virtual DbSet<Monster_Type> Monster_Type { get; set; }
        public virtual DbSet<Monster_Weaknesses> Monster_Weaknesses { get; set; }
        public virtual DbSet<Trait> Traits { get; set; }
    }
}
